
name: Linux Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: LinuxBuild
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Installing LibVLC
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
          
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm
          
      - name: Compile
        run: |
          haxelib run lime build linux
      
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinuxBuild
          path: export/release/linux/bin/
